CREATE DATABASE AddressBook;

USE AddressBook;

CREATE TABLE IF NOT EXISTS Contacts (
	ContactId INT(11) NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    Street VARCHAR(20) NOT NULL,
    City VARCHAR(20) NOT NULL,
    State VARCHAR(20) NOT NULL,
    Zip VARCHAR(20) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Email VARCHAR(20) NOT NULL,
    PRIMARY KEY (ContactId)
    ) ENGINE = InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT = 1;